name: IdleTimer
author: Rexxars
category: Utilities
tags: [behavioral, keyboard, mouse, idle, timer]
docs: http://rexxars.com/projects/idletimer/
demo: http://rexxars.com/project/idletimer/demo/
website: http://rexxars.com/
