name: IdleTimer
author: rexxars
category: Utilities
tags: [behavioral, keyboard, mouse, idle, timer]
docs: http://rexxars.com/project/idletimer/
demo: http://rexxars.com/project/idletimer/demo/
website: http://rexxars.com/
